name: publish

on:
  push:
    # tags:
    #   - 'v*'
    branches:
      - dev

jobs:
  # publish-npm:
  #   runs-on: ${{ matrix.os }}
  #
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest]
  #       node: [14]
  #
  #   name: ${{ matrix.os }} Node ${{ matrix.node }} publish npm
  #
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0
  #
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: ${{ matrix.node }}
  #         registry-url: https://registry.npmjs.org/
  #
  #     - name: Get npm cache directory
  #       id: npm-cache
  #       run: |
  #         echo "::set-output name=dir::$(npm config get cache)"
  #
  #     - uses: actions/cache@v2
  #       id: cache
  #       with:
  #         path: ${{ steps.npm-cache.outputs.dir }}
  #         key: ${{ runner.os }}-node-${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}
  #         restore-keys: |
  #           ${{ runner.os }}-node-${{ matrix.node }}-
  #           ${{ runner.os }}-node-
  #
  #     - name: publish
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  #       run: |
  #         set -e
  #         npm ci
  #         npm run test:before-publish
  #         npm publish

  publish-docker:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    name: ${{ matrix.os }} Node ${{ matrix.node }} publish docker

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Prepare
        id: prep
        if: github.event_name != 'pull_request'
        run: |
          set -ex
          DOCKER_IMAGE=pabra/inwx-apply
          BRANCH="${GITHUB_REF#refs/heads/}"
          SHORT_SHA="${GITHUB_SHA:0:7}"
          COMMITS="$( git rev-list --count "${BRANCH}" )"
          SUBJECT="$( git show --no-patch --format=%s ${GITHUB_SHA} )"

          if [ "${BRANCH}" = 'dev' ]; then
            TAGS="${DOCKER_IMAGE}:${BRANCH}-${COMMITS}-${SHORT_SHA}"
            TAGS="${TAGS},${DOCKER_IMAGE}:edge"
          elif [ "${BRANCH}" = 'master' ]; then
            TAGS="${DOCKER_IMAGE}:${BRANCH}-${COMMITS}-${SHORT_SHA}"
          else
            TAGS=''
          fi

          echo ::set-output name=tags::${TAGS}

      - name: debug tags
        run: |
          set -ex
          echo "tags: '${{ steps.prep.outputs.tags }}'"

      - name: Login to DockerHub
        if: github.event_name != 'pull_request' && steps.prep.outputs.tags
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        if: github.event_name != 'pull_request' && steps.prep.outputs.tags
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.prep.outputs.tags }}
          cache-from: type=registry,ref=pabra/inwx-apply:buildcache
          cache-to: type=registry,ref=pabra/inwx-apply:buildcache,mode=max
