name: unit-tests

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node: [14, 16, 17]

    name: ${{ matrix.os }} Node ${{ matrix.node }} cache

    env:
      OS: ${{ matrix.os }}
      NODE: ${{ matrix.node }}

    steps:
      - if: ${{ matrix.os == 'ubuntu-latest' || matrix.node == 16 }}
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - if: ${{ matrix.os == 'ubuntu-latest' || matrix.node == 16 }}
        uses: actions/setup-node@v3.1.0
        with:
          node-version: ${{ matrix.node }}

      - if: ${{ matrix.os != 'windows-latest' && ( matrix.os == 'ubuntu-latest' || matrix.node == 16 ) }}
        name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"

      # getting and storing cache takes about 1:20 min each on windows
      - if: ${{ matrix.os != 'windows-latest' && ( matrix.os == 'ubuntu-latest' || matrix.node == 16 ) }}
        uses: actions/cache@v2
        id: cache
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node }}-
            ${{ runner.os }}-node-

      - if: ${{ matrix.os == 'ubuntu-latest' || matrix.node == 16 }}
        run: |
          npm ci
          npm run test:after-commit

      - if: ${{ matrix.os == 'ubuntu-latest' || matrix.node == 16 }}
        uses: codecov/codecov-action@v2
        with:
          flags: unittests
          env_vars: OS,NODE
          verbose: true
